### ISSUE TITLE
8.1.3 v0.00.00: Brainstorm Default Roadmap Metadata

### ISSUE THREAD

**Issue by trainfarb** [trainfarb/trainfarb#68]
Predecessor: https://github.com/ourStoryNetwork/lp81-operations-platform/issues/28
# 1.8.1 v0.00.00: Brainstorm Default Meeting Metadata
## ourStory Problem
It's mentally draining for designers and engineers to switch from meeting to meeting with no context or agenda.

## openSource Solution
Create a simple meeting outline that using oS3's Onboarding Team Metadata as the content related to each attendee, and use Quantum MeMoir Base Code to create an agenda around the beat. Track minutes and progress during the meeting with Bullet Journal. 

## Product operatingSystem
If we organize every meeting as a YAML file, then we will find a standard structure that is informative and collapsable.
* oct00 Ecosystem Research
  * Find a video to research YAML: https://youtu.be/fwLBfZFrLgI?si=cgBHoCsJm7TkPzA-
  * Write out the metadata for a platform ecosystem
  *Work through Define PURPOSE, GROUND Operations, and INTEND Design spheres
*oct01 Platform Metadata
  * Label each verse as one of the 4 platform players & use their 0.9.0 Onboarding Metadata for each player
  * Work through OBSERVE Market and CONNECT Partners Prompts
* oct02 Streamer Product
  * Work through EXPRESS Vision and INTEGRATE Lesson Prompts
* oct03 Subscriber PoW Post (comment)
  * Review Define PURPOSE & GROUND Operations slides

### oct00 Ecosystem Research
- [x] Create a structure based on oS3 & QM Base Codes. These will be YAML Files as a final product before 
```
oS3 Base Code: Meeting Attendees (Ecosystems, Platforms, Streamers, and Sponsors)
Ecosystem:
  Platform:
    Value: 
    Challenge:
    Inspiration:
    Content:
    Song:

QM Base Code: Meeting Agenda
PURPOSE:
  GROUND:
    INTEND:
    OBSERVE:
    CONNECT:
    EXPRESS:
    INTEGRATE:
```
- [x] Save link to [Quantum MeMoir Base Code Template](https://www.quantummemoir.com/quantum-memoir-base-code)

### oct01 Platform Metadata
- [ ] Create YAML file in repository titled "8.1.3 Goal Setting Operating System" and create meeting outline
- [ ] Add YAML file contents below
```
8.1.3-goal-setting-operating-system.yml
yada yada: dsfsdaf
  blah blah: asdfasdf
```
- [ ] Add link from YAML file to Sponsors page as Proof-of-Work

### oct02 Streamer Product
- [ ] Create GitHub Project for oS3:QM:ABC 8.1.3 Goal Setting Operating System v0.00 (Each Prompt is an issue and the whole project is a single meeting. Completely atomized except for the meeting attendees. All Platform Players are listed in the same 4 issues. Project should closely reflect the metadata structure. 
- [ ] For Indents use "//observe:" or "/ground:" since GitHub Projects doesn't have nesting. 
- [ ] Add GitHub Project link to Sponsors Page as Proof-of-Work

### oct03 Sponsor PoW Post
- [ ] Share post describing this work and directing people to the sponsorship page as a call to action (beat is based on what was produced - metadata, so book quote is the beat) - book quote from LAND or...something else
- [ ] Share link from post on twitter, instagram, & Linkedin here
- [ ] Copy this work to Sponsor's stream
- [ ] Paste link from sponsor comment here to close it out

Quantum Pincer `to`: https://github.com/users/trainfarb/projects/1/views/1?pane=issue&itemId=37944938

> The above notes have been shifted to the 1.8.3 sphere so governance can handle agendas that govern meeting and 8.1.3 can handle stringing the meeting agendas/minutes together in a logical roadmap.

Quantum Pincer `from`: https://github.com/deg-entreprises/lp81-operations-platform/issues/16#issuecomment-1708923855

Roadmap is defined by nested meetings:
* Tier 0 Meeting - Github Organization - Full Open Source Platform Ecosystem Lifecycle
  * Tier 1 Meetings - GitHub Repository - Each platform / Longplay is a meeting
    * Tier 2 Meetings - GitHub Repository Folder - Each Project Metadata / epicPlaylist is a meeting
      * Tier 3 Meetings - GitHub Project - Each Project / verse is a meeting
        * Tier 4 Meetings - GitHub Issue - Each Issue / beatDrop is a meeting
          * Tier 5 Meetings - GitHub Comments - Each comment / beat is a meeting

- [ ] Create 8.1.3 v0.00 MVP Project
- [ ] Link to 8.1.3 v0.00 MVP Project here
